### ISSUE TITLE
As an organizer I can email the entire list of participants.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/chapter#99] opened 2019-10-20 23:51 UTC
Implementation details:

- UI: /dashboard/events will need buttons to email all subscribed users after a confirm dialog has been clicked through
- Sending the email: we already have a `sendEventInvite` mutation https://github.com/freeCodeCamp/chapter/blob/8ef1db39c5137e5dd49f5dd974107b57f3eda231/server/controllers/Events/resolver.ts#L259 
- It should be possible to reuse most of that, but allow the emails sent to vary.

**Comment by papigers** [comment] 2019-11-11 01:02
I'm on it, I'll start working on the UI components.

In the meantime, how do we plan to send the emails? use an email service like SendGrid? use environment variables that will configure an SMTP endpoint to which we will send emails via `nodemailer`?

**Comment by Zeko369** [comment] 2019-11-11 07:22
@papigers there is a PR for that already #146

**Comment by allella** [comment] 2020-02-17 18:03
Linking these for when someone starts working on email sending.

#283 #146 are related to the transactional email needed to send over SMTP.

Also, some questions which may be relevant were raised in https://github.com/freeCodeCamp/chapter/issues/320#issuecomment-581653505

**Comment by Ravichandra-C** [comment] 2021-09-20 11:40
@allella @ojeytonwilliams Can I work on this issue?

**Comment by ojeytonwilliams** [comment] 2021-09-20 16:37
> an email to all members with an active rsvp for a specific event?

@allella That's my understanding, yes. The existing `sendEventInvite` code *should* handle that already, but we need a way of triggering that via a button press.  At the moment it's just triggered by new event creation.

> Do we have to add a column for a buttons to send emails to all participants in the dashboard/events page ?

@Ravichandra-C I think we'd at least want a button on `/dashboard/events/[id]` and possibly on `/dashboard/events/` itself, but the UI on that page is already a little cluttered.

For this issue, I think it would be enough to add a button to the `/dashboard/events/[id]` page.  

Separately, but somewhat related, we'd want to make it more obvious how to get from  `/dashboard/events/` to specific events.  It's possible right now, but you have to click on the name.  This isn't particularly intuitive.  Anyways, this is just something to bear in mind - it's not a requirement for closing this issue, imo.

**Comment by allella** [comment] 2021-09-20 17:07
#267 is on the [roadmap](https://github.com/freeCodeCamp/chapter/labels/Roadmap) as a future feature for emailing all _members_ of a _chapter_.

So, I think we're all in agreement that this will be for emailing _members_ who have an _rsvp_ for a specific _event_.

@Ravichandra-C For a button title, I think "Email All Event RSVPs"  or "Email All Event Attendees" would be good enough to start.

**Comment by allella** [comment] 2021-09-20 17:11
One other thought about this issue, is that some _events_ will have _members_ on the waitlist and it may not be clear to the _organizer_ if they are about to email just confirmed reservations, or if that includes those on the waitlist.

We could possibly have a radio form field, or similar, to select between 

- Confirmed Only
- Waitlist Only
- Confirmed + Waitlist

Though, if that complicates things, we can start with emailing Confirmed + Waitlist and put a note on the page specifying that the email will go to both Confirmed + Waitlist.

**Comment by allella** [comment] 2021-09-20 17:13
I'm reminded that we also have an ["Interested" field for RSVPs](https://opensource.freecodecamp.org/chapter/tables/rsvps.html), so that could be another possible category to differentiate.  Plus, there may be a use case for emailing canceled RSVPs.

So, perhaps we'd want checkboxes to allow for selecting 1 or more of

- Confirmed
- Waitlist
- Interested
- Canceled

**Comment by Ravichandra-C** [comment] 2021-09-21 13:20
@allella @ojeytonwilliams . Thanks a lot for your comments.

I'll add a "Email Attendees " button on /dashboard/events/[id] page and show check boxes in a Modal with Send Button.

Attached the screenshot where the button willbe on the /dashboard/events/[id] page
![image](https://user-images.githubusercontent.com/17808008/134177915-6eabd2ce-9071-4b58-8e56-e5266b45ba06.png)

Could you please let me know if that is fine?

**Comment by ojeytonwilliams** [comment] 2021-09-21 13:49
Sounds good to me. The only point I disagree on is that we should just email people that are _interested_. If they've opted out, that has to be respected.

**Comment by allella** [comment] 2021-09-21 15:27
Actually, the _interested_ field is intended to store the "subscription" preference of the rsvp? 

@ojeytonwilliams and I [agreed to change the _rvsp.interested_ and _user_chapter_role.interested_ fields to be named rsvp.subscribed and user_chapter_role.subscribed](https://github.com/freeCodeCamp/chapter/pull/641#issuecomment-878104966), but that may have gotten lost in the effort to focus PR #641.

We also agreed that we might, eventually, decide to move rsvp.subscribed to user_event_roles.subscribed, allowing for subscriptions for an event based on the role (member, organizer, sponsor).

@ojeytonwilliams I haven't run SchemaSpy since you did the work on #695, so I haven't seen if the change to _.subscribed_ field names made it into another PR.

**Comment by Ravichandra-C** [comment] 2021-09-22 05:52
@ojeytonwilliams @allella Do we have any mutation to send the email to selected set of people? Like if I want to send an email to Interested only, Do we have a mutation for that?

Looks like SendEvenInvite Mutation is sending the email to all the members in the Confirmed and waitlist?.

**Comment by ojeytonwilliams** [comment] 2021-09-22 07:21
@Ravichandra-C that's right - the current mutation only filters out people that are not _interested_.

I'd recommend modifying that mutation to take the additional options as an argument.

**Comment by Ravichandra-C** [comment] 2021-09-23 13:18
@allella @ojeytonwilliams 

I've implemented the functionality as shown in the screenshots below.

Interested checkbox is enabled by default.

![image](https://user-images.githubusercontent.com/17808008/134513639-b62e6d32-67cc-4862-a971-44906338ddf0.png)

If User un selects all check boxes and click on Send he will be presented an error message  as shown in the screenshot.

![image](https://user-images.githubusercontent.com/17808008/134513919-fd68cf21-3b5a-400a-9b3a-46489805953c.png)


Could you please let me know if this looks good?

**Comment by Ravichandra-C** [comment] 2021-09-23 16:52
@ojeytonwilliams , I think there is a confusion in the functionality.

interested checkbox will not send mail to people who have **_interested_** set to false. It will only send email to people who have **_interested_** set to to true on that event's chapter level (.ie people who choose to follow the events in that chapter).

Confirmed will send the email to Only Confirmed participants of the event.

Waitlist will send the email to only participants on the waitlist of that event. We are not sending the email to people who have interested set to false.

>Could you remove the 'interested' checkbox in favour of 'cancelled'

Do you still  want me to replace the interested checkbox with Cancelled?

If Yes, Could you please let me know to whom the email should be sent when we choose _Cancelled_?

**Comment by ojeytonwilliams** [comment] 2021-09-23 17:27
Sorry, @Ravichandra-C part of the issue is that I'm still working on the _events.interested_ (soon to be _events.subscribed_!) functionality.  All being well I should have that done fairly soon.

Anyways, the way I see things is this: if a user unsubscribes from a chapter (i.e. _user_chapter_role.interest_ = false for that user), that chapter should stop emailing them entirely.  That means we should always filter out users who are not interested in that chapter.

Once I'm done with the _user_event_role.interested_ implementation, we can similarly filter out people that are no longer interested in a particular event.  But the same principle applies, it shouldn't be possible to email these people, since that would be spam.

> Do you still want me to replace the interested checkbox with Cancelled?
>
> If Yes, Could you please let me know to whom the email should be sent when we choose Cancelled?

@allella can confirm/deny, but I think it's a simple as users who have _rsvp.cancelled_ = true and are still _interested_

**Comment by Ravichandra-C** [comment] 2021-09-23 17:42
@ojeytonwilliams, Thank a lot for your clarification.

>but I think it's a simple as users who have rsvp.cancelled = true and are still interested

So when organizer selected the Cancelled checkbox, Should we email to people whose rsvps.cancelled=true and user_chapter_role.interested=true?

**Comment by ojeytonwilliams** [comment] 2021-09-23 21:03
You're very welcome, thanks for taking the time to discuss this.

> So when organizer selected the Cancelled checkbox, Should we email to people whose rsvps.cancelled=true and user_chapter_role.interested=true?

That makes sense to me, yeah.

**Comment by allella** [comment] 2021-09-23 21:56
@ojeytonwilliams I haven't reviewed the [MVP issue for unsubscribing](https://github.com/freeCodeCamp/chapter/issues/274), but I'm wondering about a use case where a _user_ can unsubscribe from a _chapter_ but still remain subscribed to specific events, via an RSVP.   For example, someone might not want the general announcements for new monthly meetup _events_ or other general _chapter_ messages from an _organizer_, but they may rsvp for an annual event and still expect to get notices about that specific event.  I think that's why we have rsvp.interested, so opt-in / opt-in can be specific to the _event_.

Previous conversations suggested we'd have an unsubscribe link in the bottom of any emails, even allowing a _user_ to unsubscribe from a chapter or rsvp / event by clicking a link event even if they weren't logged in, for convenience.  So, if we made that process easy it shouldn't be spammy.  Also, I assume we'd present the _user_ with a form field / slider when they create the _RSVP_.  Perhaps we could default that to whatever their chapter_user_role.interested value is, but still allow them to change the default value when they _rsvp_.

@Ravichandra-C the _rsvp.interested_ field will be something the _user_ can toggle on or off from a link in an email or by visiting the event page.

As you mentioned, there are possibly situations where we'd want to email a user even if they opted out of communications for the event.  Cancellation of an event seems reasonable. However, the _rsvp.canceled_ field would presumably be used to save that a _user_ or _organizer_ had cancelled an _RSVP_ for a specific attendee, and not related to the [separate user story for when an organizer cancels an event](https://github.com/freeCodeCamp/chapter/issues/100).

So, for this user story and interface, I think we'd still want to send email only if _rsvp.interested = true_

Confirmed - _rsvp.confirmed_ = true && _rsvp.interested_ = true 
Waitlist - _rsvp.on_waitlist_ = true && _rsvp.interested_ = true
Canceled - _rsvp.canceled_ = true && _rsvp.interested_ = true

Thanks for the great work on this issue.

**Comment by Ravichandra-C** [comment] 2021-09-24 08:47
@allella @ojeytonwilliams , Thank you for your comments.

I've updated the label of the checkbox from interested to cancelled.

![image](https://user-images.githubusercontent.com/17808008/134644864-8d9e1122-0877-4640-804e-ca7f917a992f.png)


> Confirmed - _rsvp.confirmed_ = true && _rsvp.interested_ = true
> Waitlist - _rsvp.on_waitlist_ = true && _rsvp.interested_ = true
> Canceled - _rsvp.canceled_ = true && _rsvp.interested_ = true

and I've also updated the resolver logic according to above logic , Only change is that since we don't have rsvp.confirmed for confirmed I'm checking if (!rsvp.onwaitlist&&!rsvp.cancelled)&&rsvp.interested

Could you please let me know if that is fine?

**Comment by ojeytonwilliams** [comment] 2021-09-24 09:42
> I'm wondering about a use case where a user can unsubscribe from a chapter but still remain subscribed to specific events, via an RSVP

I'm pondering that, too.  It seems to me that it's important that it's both clear to users what will happen when the subscribe/unsubscribe and clear to developers what each flag in the db is intended to do.  

From a user perspective, if I unsubscribe from a Chapter, I would expect that Chapter to stop emailing me.  If I *then* subscribed to a specific event, I would expect to opt into emails. For example, if I RSVP to an event it could ask "You're not subscribed to this Chapter, would you like to be notified about this event?". Then I would get emails about *that* event, but nothing else from the Chapter.  And if I reversed the order, I would expect to stop getting emails entirely, including from the event I just subscribed to.  In that case it should warn the user "This will stop all communications from this Chapter, are you sure?".

From a developer perspective, I need to know what the _interested/subscribed_ columns means.  The more I think about this, the more I'm leaning towards having _user_chapter_role.interested_ and _user_event_role.subscribed_.  The former would control if a user is notified about new events (and if they're asked if they want to subscribe to an event). The latter would control if they get emails about a specific event.  Then, if a user unsubscribes from a Chapter, that would flip the _user_chapter_role.interested_ to false and _user_event_role.subscribed_ would also be set false for all that Chapter's events.  And, obviously, subscribing to a specific event would only change the _user_event_role.subscribed_ value.

Finally, I think we'd want _user_event_role.subscribed_ instead of _rsvp.interested_, since _rsvp_ focuses on if the user wants to go to an event and _user_event_role_ captures their permissions and settings.  Until we have more settings to worry about, it seems fine to lump them together.

> I've updated the changes and pushed them to PR #712 . Could you please review and let me know if that is fine?

Awesome, thanks @Ravichandra-C, I'll do that now!  We might need to tweak things slightly, as we settle on exactly what we want the db + UX to be, but the PR as described sounds good and we can always keep iterating after merging.

**Comment by Ravichandra-C** [comment] 2021-09-24 12:19
Sure, Thank you! @ojeytonwilliams

**Comment by allella** [comment] 2021-09-25 16:06
I mostly agree with the field names. I think we could use _subscribed_ on both _event_ and _chapter_ tables, but if we want to keep _interested_ for _chapters_ and _subscribed_ for events, then that's fine.  The two terms still lack some context to the developer. Unless we're going to make the field names longer and more to the point, then they might always be a bit confusing.  I think the code, comments and UI may have to provide the necessary context regardless of what we call it.

I've added a link back to the last comment on the #274 since it applies as much, if not more, to that issue.

We're still in agreement that _user_event_role.subscribed_ instead of _rsvp.interested_ would give more flexibility to a _user_ with multiple roles on the same event. Though, I'd leave it up to Oliver if we're going to tackle that under this issue, or when we get further.

**Comment by ojeytonwilliams** [comment] 2021-09-27 09:28
Great, I think we're basically on the same page.

>  I think the code, comments and UI may have to provide the necessary context regardless of what we call it.

That's fair.  I've been trying to use comments less liberally, but this does seem like a case where we're not going to capture the nuance with a good variable name.

> We're still in agreement that user_event_role.subscribed instead of rsvp.interested would give more flexibility to a user with multiple roles on the same event. Though, I'd leave it up to Oliver if we're going to tackle that under this issue, or when we get further.

I'll handle that separately.

**Closed** 2021-09-27 13:10 UTC
Labels: Help Wanted, MVP, UI/UX, Email, Good First Issue
