### ISSUE TITLE
Add user_roles table for organizers and admins

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/chapter#296] opened 2019-12-15 22:26 UTC
Create a `user_roles` table with `id` and `type` as string and reference the `id` of `user_roles` via `users` table.

**Comment by AryanJ-NYC** [comment] 2019-12-16 00:53
Relates to https://github.com/freeCodeCamp/chapter/issues/16.

**Comment by madaleneaza-design** [comment] 2019-12-24 00:29
Based on the discussion in Discord, I have explained what I thought  each role (organiser and admin) could do:

**Admin**
Only the administrator is able to do create chapters, although they have full control of what is going on in the Chapter instance, they probably will have little involvement in specific chapters (such as CRUD events, managing chapter members unless the situation is high-level priority). Other than that, they aim to focus on admin tasks and keeping the Chapter sailing afloat.

**Organiser**
the chapter organiser focuses on managing and organising events for the chapter (and events) they are assigned to, that includes any kind of tasks relating to their chapter only. 

Also, this can be useful for chapters to have more than one organiser (or at least a co-organiser), as unforeseen circumstances may occur and a particular organiser may not be able to do their role, at least the co-organiser can fill in the gap (even if it is just temporarily).

**Comment by vkWeb** [comment] 2019-12-24 07:29
@madaleneaza-design @allella I think the organizers shouldn't be able to add other organizers to the chapter they are appointed to. Suppose fCC is the organization and Quincy is the admin. Now the admin appointed me as an organizer for fCC Delhi (a chapter under fCC). If I add Tim as an organizer of fCC Delhi then we will need to put there a feature to inform Quincy that Tim has been added as an organizer for fCC Delhi by me because in Quincy's mind I should be the only organizer. 

We can make this thing more feature-rich by giving admin an option to "allow the organizer to add more organizers" but I don't think this should be in our MVP. So only administrators should be able to add new organizers to keep things a bit straightforward for our MVP. If the admin needs help or is busy then he/she can add more admin(s).

So here's my take on the permissions of administrators and organizers: 

**Administrators**
- can add, remove admins
- can add, remove organizers for a chapter
- can CRUD chapters and its details
- can CRUD any chapters' event and its details
- can email, ban any chapter organizer 
- can email, ban users
  - can email or ban only when the user has attended an event under any of the chapters
  - can email only when the user has subscribed to one of the chapter
- has full control over the Chapter instance and site-wide settings

**Organizers**
- can CRUD events and its details only under the chapter they are appointed to
- can email, ban users under the chapter they are appointed to
  - can email or ban only when the user has attended an event under that chapter
  - can email only when the user has subscribed to the chapter

@allella @madaleneaza-design how does that look? Tell me If I missed something.

**Comment by allella** [comment] 2019-12-24 16:05
@vkWeb 
Looks good.

I'm hip to holding back the "organizers adding other organizers to their _chapter_"  and keeping it out of the MVP.

I feel this will be a desirable future (post-MVP) feature. As you said, if it's an option to turn delegation on / off then the admin could pick between tighter control of organizers, or delegating that permission to organizers.

**Comment by madaleneaza-design** [comment] 2019-12-24 20:44
@vkWeb These are really good details and points you have written. 🙂 

I really like your suggestion of the feature, which is " giving admin an option to "allow the organizer to add more organizers". 

The reason being is we must remember that every user (organisation) comes in different sizes, and structures of running their system. So, not all organisations will agree with our suggestions such as one may not like the idea of organisers being allowed to add another organiser (my suggestion). That could be the same for your suggestion of admins adding other admins, some may like that idea, but not to have the full control of the Chapter instance (basically you may get feedback from users that they may want an assistant admin where it holds more control that organisers, but less than the admin - this could end up being another feature to be considered. 

However, I do understand that there may be a limit to what we can provide, which is why the vital part of the UX design process is **user research** and that is to gather insights of both qualitative research (*why* the user prefers that feature) and quantitative research (*how many* users prefers that feature).

Therefore, I can agree with @allella on this feature being the future MVP, and go with whatever will be decided for now and hopefully with some feedback from users for any improvement, we can work on it then.

**Comment by allella** [comment] 2020-01-16 09:52
Being that this is a prerequisite for #16 I wanted to see if I can help keep it going for @AryanJ-NYC 

@vkWeb started working on a user_role table in #253 and that was rolled into this issue because it wasn't as fleshed out as the rest of that PR.

@timmyichen had mentioned having a [chapter_id key on the user_role](https://github.com/freeCodeCamp/chapter/pull/253#issuecomment-555193444)
to go along with the user_role.id and user_role.type. 

The "type" lead into whether to specify these values as an enum or a string and @Zeko369 weighed in on using strings over enums for simplicity.  @timmyichen does that should good to you or was there a specific migrations concern?

I assume the "type" would be defined in the [DDL](https://github.com/freeCodeCamp/chapter/blob/master/data/ddl.sql), similar to the sponsor_type, but as a string. Is that right?

```
create type sponsor_type as enum
('FOOD', 'VENUE', 'OTHER');
``` 
#313 was just merged in (by me, sorry, not sorry) and it aimed to provide clarity on the [user role terminology in the README](https://github.com/freeCodeCamp/chapter#terminology).

Hopefully, that's enough to get us chatting again and move along on the issues related to _administrator_ and _organizer_ and _user_ roles.  I think those are the three roles for the MVP.

Now, all we have to decide is organizer vs organiser :)

**Comment by allella** [comment] 2020-01-16 09:54
And, even though this is more about authorization then authentication, I feel @vaibhavsingh97 should weigh in since he was looking at #305

**Comment by AryanJ-NYC** [comment] 2020-01-17 04:31
Will a user only have one role?

**Comment by AryanJ-NYC** [comment] 2020-01-17 04:38
Either way, please assign this to me.

**Comment by allella** [comment] 2020-01-17 06:44
@AryanJ-NYC I think it's safe to assume a _user_ might have more than one record in the _user_role_ table. 

For instance, if a _user_ is an _organizer_ or two different _chapters_ then they'd likely need a record for each _user_ + _role_ + _chapter_ combination because being an _organizer_ for one _chapter_ doesn't mean you can organize all the _organization_'s _chapters_

**Comment by allella** [comment] 2020-01-17 06:58
Also, I was thinking that for the regular user, who is not an organizer or an administrator, it may be helpful if we call their role something like _member_. 

If we didn't differentiate the default / base user role, then we'd potentially end up saying things like "a basic _user_ has the role of _user_", which is likely to get rather confusing.

If the basic / default role of a user is the _member_ role, then we could describe roles like:
- a _user_ with the role of _administrator_ can create new _chapters_
- a _user_ with the role of _organizer_ can email _chapter_ members
- a _user_ with the role of _member_ can _RSVP_ for an _event_

@madaleneaza-design @vkWeb and I [described the administrator and organizer roles above on this thread](https://github.com/freeCodeCamp/chapter/issues/296#issuecomment-568613421), but we didn't talk about the default/base role, which I'm proposing we don't call the _user_ role, since _user_ is already an entity.

Thoughts on these role names? @AryanJ-NYC @madaleneaza-design @vkWeb @Zeko369 @timmyichen @vaibhavsingh97

**Comment by AryanJ-NYC** [comment] 2020-01-17 07:08
I like the names a lot. Just to confirm and make sure I have it straight:

* A user will have exactly one role per chapter they belong to (they cannot be both an organizer and an admin of a chapter).
  * That assumes that admins have all the permissions thag organizers have (and more) who, in turn, have all the permissions that user have (and more).

Does this ticket entail setting up the user role permissions as well?

**Comment by allella** [comment] 2020-01-17 07:39
@AryanJ-NYC one complication with the _roles_, no matter what we call them, is that the _administrator_ is the _administrator_ for the entire _organization_ and not just a single _chapter_.  As the "super user" we don't gain anything by mapping a _user_ as an _administrator_ for every single _chapter_.

So, I'm not immediately clear if a _user_roles_ table is ideal, or even necessary for capturing the _administrator_ role. Though, unless we're going to assume _user_ # 1 is always the _administrator_, then we'd need to store the admin's user ID somewhere in the configuration or database.

For a moment, let's assume user  # 1 is always the _administrator_, then would we prefer to scrap the _user_roles_ table and extend [the existing _user_chapters_ table](https://github.com/freeCodeCamp/chapter/blob/master/data/schema.png) since it already maps _users_ to _chapters_?

```
user_chapter.user_id
user_chapter.chapter_id
user_chapter.role_id
```

I think the reason this is a bit confusing is the _administrator_ role is more of a system role for the entire organization, whereas the _organizer_ and _member_ roles would be more specific to a _chapter_.

**Comment by vkWeb** [comment] 2020-01-17 09:00
>Also, I was thinking that for the regular user, who is not an organizer or an administrator, it may be helpful if we call their role something like member. 

@allella Thanks for starting the conversation flow after Christmas break :) 

So you mean if they sign up in the organization, they become its member? https://github.com/freeCodeCamp/chapter/issues/106 will conflict with naming discussed here. So we need to clear this confusion.

> A user will have exactly one role per chapter they belong to (they cannot be both an organizer and an admin of a chapter).

> That assumes that admins have all the permissions thag organizers have (and more) who, in turn, have all the permissions that user have (and more).

Exactly @AryanJ-NYC. But users (normal visitors) won't have any special permission I believe.

**Comment by AryanJ-NYC** [comment] 2020-01-17 14:07
@allella one idea would be an `is_admin` boolean field on the user model while having the `user_chapter_roles`table be responsible for only member roles and member membership to organization (if there exists a `user_id` and `org_id` combo inside the table, then the user is a member of that org).

**Comment by allella** [comment] 2020-01-17 19:01
@AryanJ-NYC yes, I agree on a _user.is_admin_ boolean.  I'm not sure we'll have other _organization_-level roles besides an _administrator_. An admin flag would keep it simple and still allow an _organization_ to have one or more admins.  Plus, this avoids the confusion of mixing system-wide and _chapter_-level roles.

I think @AryanJ-NYC  was suggesting we'd rename the user_chapters table to user_chapter_roles and I think that will work. Would this be called _user_chapter_roles_ or _user_chapter**s**__roles_?

@vkWeb I think the title from #106 is hinting at the need for a _member_ role because we are naturally referring to a basic _user_ as a _ chapter member_.

The _user_ is an entity, but they can also have specific roles related to a specific _chapter_.  If someone signs up for a _user_ account and never joins a _chapter_ then they are still a _user_ with no role. When a _user_ joins a _chapter_ they inherit a role of _member_ and a record is added to the _user_chapter(s)__roles_ table.

Thoughts?

**Comment by madaleneaza-design** [comment] 2020-01-18 01:36
I am not exactly sure if this is relevant to this issue, but last week as part of the UX user research, I created a "user role hierarchy" map (see the photo).

![user role map](https://user-images.githubusercontent.com/38219468/72656378-c321c480-3992-11ea-95cd-854c2420d9aa.jpg)

Each post-it is a user role and each colour indicates a "confirmation" status:

- Green - we are definitely having this role
- Yellow - it is favoured and likely to have this role but not yet officially confirmed
- Orange - either not likely to have this at this moment but possible in later future **OR** it has not been discussed yet.

So, the co-organiser is the only one where it is not happening, but sitting on the shelves i in case it may ever be needed. The rest of the orange post-its are the ones I have not yet to discuss it with you.

This is only a very basic map, but wanted to see if this is useful before I go any further and also it may help to give you some ideas too 🤷🏼‍♀️

PS: I hope you can read my handwriting!

**Comment by allella** [comment] 2020-01-18 06:28
Thanks @madaleneaza-design  I think that we're all using the word _member_ without thinking about it tells use that _member_ is a good name for the basic _chapter_ role.

We'll need to update [the README terminology](https://github.com/freeCodeCamp/chapter#terminology) to differentiate the _user_ and _member_ terminology.  I think it's pretty easy to understand _administrator_, _organiser_, and _member_ are the possible _roles_ of a _user_.

**Comment by allella** [comment] 2020-01-18 06:33
@madaleneaza-design also what do you think about

- user who is a chapter member
- user with no chapter role
- visitor

to describe the bottom row of sticky notes (from left to right)?

**Comment by madaleneaza-design** [comment] 2020-01-18 16:16
> Thanks @madaleneaza-design I think that we're all using the word member without thinking about it tells use that member is a good name for the basic chapter role.
>
> We'll need to update the README terminology to differentiate the user and member terminology. I think it's pretty easy to understand administrator, organiser, and member are the possible roles of a user.

Well, I definitely wouldn't use the word user to describe it as a member. The word user is too broad in the sense of it could be an admin, an organiser or, a visitor _using_ the Chapter. Just a thought. 🙂 

> @madaleneaza-design also what do you think about
>
> user who is a chapter member
> user with no chapter role
> visitor

To simplify the name of the user role? Sure, they do make sense. I would only suggest adding a small description (say, for documentation) to state who they can be implied as. This is in case someone who may not fully understand or realise the details of the role.

**Comment by madaleneaza-design** [comment] 2020-01-18 16:50
> Now, all we have to decide is organizer vs organiser :)

@allella Definitely organizer. 

Because most people whose first language is not English, when they are being taught, the language is set in American standard rather than British. However, this is both merely an opinion and down to personal experience.

**Comment by allella** [comment] 2020-01-18 20:18
@madaleneaza-design yes, the notes about visitors and types of user would be more applicable to a README or how we talk about them.

I'd suggest a _visitor_ is not a _user_ (in the technical sense) since they aren't represented in the _user_ table.  Anybody who has a login is a _user_ with a 0 or 1 role per chapter, but a visitor is not a _user_ for internal conversations and they have no _role_.

Thoughts on that distinction?

**Comment by madaleneaza-design** [comment] 2020-01-18 22:50
> I'd suggest a visitor is not a user (in the technical sense) since they aren't represented in the user table. Anybody who has a login is a user with 0 or 1 role per chapter, but a visitor is not a user for internal conversations and they have no role.

@allella Ah got you now and yes, I agree. 

The visitor wouldn't be able to **use** any internal features and controls such as making comments. Even if they were able to RSVP, it will eventually lead them to be a _user_ (by signing up for a _user_ account). 

I would suggest that it could also be explained in the README.md the differences between a user (a  technical term referring to a user table) and a member (a general/UX term referring to a user journey/story) for the sake of not be used interchangeably, leading to confusion. Just a thought 🙂

**Comment by allella** [comment] 2020-01-19 16:17
Yes, I agree we should differentiate _user_ and _member_ on the README. I'll create a PR.

**Comment by allella** [comment] 2020-02-09 22:21
A start list of [Administrator FAQs](https://github.com/freeCodeCamp/chapter/wiki/Administrator-FAQs) have been roughed in on a wiki page.  Feel free to edit the wiki or suggest more questions admins might have either here or on Discord.

**Comment by allella** [comment] 2020-02-12 07:15
There was reference to a "super admin" in the Figma comments. However, @tomiiide agreed "an admin is an admin".

So, to recap and pinging @Zeko369 @timmyichen in case they missed this conversation.

There currently is no user roles table, which is this issue exists.

The suggestions above yielded the desire to add a "user_chapter_role" table since roles like _organizer_ and _member_ are specific to each _chapters_.

Then, (via @AryanJ-NYC ) we came up with an _is_admin_ flag on the user table to toggle on a system-level admin "role" since trying to make a system-wide admin wouldn't fit well in a _user_chapter_roles_ table. 

When the instance is deployed we'll need a "user # 1" concept which will automatically have _user.is_admin_ set to TRUE.

If / as other users are invited and "user # 1" sets the user.is_admin flag on them to TRUE then they would have the same permissions as user # 1.

Based on this conversation do we want to pick a common terminology to refer to "user # 1" / "super admin".

I don't really like either of them, so I'm hoping someone has a better suggestion to define this initial, automatic-admin user.

**Comment by allella** [comment] 2020-02-12 07:45
More thoughts / questions regarding "what do we call the person who setups up the instance and becomes the first user".

@tomiiide and I were talking and he suggested owner or creator.

I thought perhaps "instance owner" or "instance creator" could work as a term.

This person would also be the one setting up the hosting for the Docker and probably registering 3rd party services, doing the configuration, and more.   So, perhaps we need to give them a unique name.

They will certainly be an _administrator_, but one with the special job of kick-starting the initial instance.

**Comment by timmyichen** [comment] 2020-02-12 08:23
Creator works in this case. I'll throw up a PR for the following:

* New table: `user_chapter_role` with possible values "organizer", "member"
* New table: `user_global_role` with possible values "creator", "admin"

**Comment by allella** [comment] 2020-02-12 15:27
Thanks @timmyichen  I'm not opposed to the global roles, but do we think that's going to complicate the permissions and logic versus having the is_admin flag?

Obviously, it gives more flexibility, but I wonder if the creator and administrator roles would have any different permissions where we need two roles.

**Comment by Zeko369** [comment] 2020-02-12 17:29
I think that @timmyichen suggestion is better because we can easily add helpers to the user class to have `user.isAdmin` and `user.isCreator`.

Also we should add possible value to `user_global_role`: "member" or "user" for the default role.
Also maybe we could just have it as a `roleId` on the user and have a enum with roles and just have every higher role inherit the child (organiser has everything that member has)

**Comment by timmyichen** [comment] 2020-02-12 17:34
> Obviously, it gives more flexibility, but I wonder if the creator and administrator roles would have any different permissions where we need two roles.

Admins probably shouldn't be able to invite other admins; that should solely be within the hands of Creator.

**Comment by allella** [comment] 2020-02-12 17:45
@Zeko369 do we want to keep the user booleans if we have a `user_global_role` table with an "owner" role.  Does that make it easier to lookup the permissions, or is it redundant and something that might get out of sync.


@timmyichen yes, if we assume only an _owner_ can add more admins, then that would make a place for an "owner" role, or the isAdmin / isOwner flags.  Heretofore, we've been operating on the premise that and admin is an admin.

It's not uncommon to see "_owner_" in hosting platforms, so I guess it's a decent expectation to follow. If that's the case then the first user of the system would be differentiated by more than just the initial creation, so perhaps "_owner_" is a better role/term than "_creator_" given these new assumptions.

> Also we should add possible value to user_global_role: "member" or "user" for the default role.

The "_member_" and "_organizer_" roles obviously make more sense in the context of `user_chapter_roles` table, so I don't see having those go into `user_global_role`

Since "_user_" is a table already I don't see a need to having people be a "role" of _user_ in `user_global_role`. If they exist in the user table then they are a user, but there's no special permissions of being a user.  

`could just have it as a roleId on the user and have a enum with roles and just have every higher role inherit the child (organiser has everything that member has)`
Parent-child relationships always tend to complicate things in the code, so my gut is to always look for a simple, elegant solution using just having people have one role per instance or chapter.

**Comment by timmyichen** [comment] 2020-02-12 18:13
No booleans would be necessary here.  Lookups are slightly more costly but it shouldn't matter given the admin/owner role will not be checked very often.  Also, if we're going to have 2 or more related boolean fields on an row, more often times than not it should go into its own enum table unless quick lookups are essential.

No need to do any role inheritance.  A chapter organizer will have two entries in the `user_chapter_roles` for `member` and `organizer`.

**Comment by allella** [comment] 2020-02-12 18:20
Okay, so to summarize:

- New table: `user_chapter_role` with possible _role_ values _organizer_, _member_ and a user can have 0 or more _roles_ per _chapter_.
- New table: `user_global_role` with possible _role_ values _owner_, administrator
- Update the README to describe the _role_ of _owner_  to differentiate it for a typical _administrator_

**Comment by allella** [comment] 2020-02-12 19:49
Just for consistency with the vocabulary, would we consider `user_instance_role` instead of `user_global_role`  ?  @timmyichen  @Zeko369

**Comment by allella** [comment] 2020-02-12 20:07
@vkWeb @AryanJ-NYC @madaleneaza-design are you all hip to https://github.com/freeCodeCamp/chapter/issues/296#issuecomment-585347150  ?

**Comment by AryanJ-NYC** [comment] 2020-02-12 20:17
@allella Acknowledged. Sorry I've been dragging my feet here!

**Comment by allella** [comment] 2020-02-12 22:46
@AryanJ-NYC  @timmyichen  may have a PR coming for this, so perhaps you can work with him, or review any PRs related to this issue.

**Comment by timmyichen** [comment] 2020-02-12 23:06
@AryanJ-NYC do you already have a branch up for this WIP?  you might be able to finish it faster haha.  Let me know if you'd rather me take it off your hands!

**Comment by vkWeb** [comment] 2020-02-13 11:47
@allella Yes, I am with you all for `creator` and `admin` roles.

**Comment by AryanJ-NYC** [comment] 2020-02-13 15:55
All good, @timmyichen. Apologies again!

**Closed** 2020-02-14 12:26 UTC
Labels: Beginner Friendly, good first issue

**Comment by allella** [comment] 2020-11-07 01:57
Reposting a comment from Discord since this is the earlier conversation and it may be helpful to a future conversation / search.

I don't think we have the permissions logic entirely figured out yet, but the ability for a *user* to post *events* on 1 or more *chapter*'s will depend on their authorization. 

Authorization will come from either of
- **user_chapter_roles** with possible role values organizer, member. A user can have 0 or more roles per chapter.
- **user_instance_roles** with possible role values owner, administrator
(lots of earlier discussion on this issue led to this summary 
https://github.com/freeCodeCamp/chapter/issues/296#issuecomment-585347150 )
which was then closed via PR: https://github.com/freeCodeCamp/chapter/pull/335

 A *user* with the role of *owner* or *administrator* would be able to CRUD *events* for all *chapters* in the *instance* and we infer that from their role in **user_instance_role**  and any *event.chapter_id* values would be from a drop-down field that populated with all values from the **chapters** table.

An *organizer* will likely have a role of **organizer** set in **user_instance_roles** but that wouldn't infer any permissions to specific *chapters*. Rather, that same *user* would only have authorization from specific entries via the **user_chapter_roles** table.  They would have 1 or more such roles in **user_instance_roles** which we assume would have been granted by the *administrator* or *owner*.   The **user_instance_roles.chapter_id** values could be what populates a form field of possible **events.chapter_id** values available when an *organizer* CRUDs an event.  Or, in the case the *organizer* only has authorization to a single *chapter*, then perhaps the app logic forces the **events.chapter_id** to that specific **chapter_id**

The role tables aren't reflected in the out-of-date schema, but here are the conversations and PR for those tables. 
https://github.com/freeCodeCamp/chapter/blob/master/docs/data/schema.png

**Comment by allella** [comment] 2020-11-07 02:03
Edited the above comment to remove the part about an organizer having a role in _user_instance_roles_. It seems we decided that role would get all it's authorizations from **user_chapter_roles**.

Though, I wouldn't entirely rule out **user_instance_roles** also accepting an _**organizer**_ role, but it's probably not necessary / advisable so we'll assume that's not the case for now.

**Comment by allella** [comment] 2022-02-01 16:20
Linking this old issue to the most recent conversation about roles tables in case anybody stumbles up the previous direction.
https://github.com/freeCodeCamp/chapter/pull/735#issuecomment-944167783
